######################################
# Makefile written by Zev Kronenberg #
#     zev.kronenberg@gmail.com       #
######################################

CXX=g++
GIT_VERSION := $(shell git describe --abbrev=4 --dirty --always)
